version: '2'
services:  
    servidor-directorio-eureka:
        container_name: servidor-directorio-eureka
        build:
            context: servidor-directorio-eureka
            dockerfile: Dockerfile
        image: servidor-directorio-eureka:latest
        ports:
            - "8761:8761"
        networks:
            - spring-cloud-network
    servidor-gateway-eureka:
        container_name: servidor-gateway-eureka
        build:
            context: servidor-gateway-eureka
            dockerfile: Dockerfile
        image: servidor-gateway-eureka:latest
        ports:
            - "8090:8090"
        networks:
            - spring-cloud-network
        depends_on:
            - servidor-directorio-eureka
    ms-users:
        container_name: ms-users
        build:
            context: ms-users
            dockerfile: Dockerfile
        image: ms-users:latest
        networks:
            - spring-cloud-network
        depends_on:
            - db
            - servidor-gateway-eureka
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
            - SPRING_DATASOURCE_USERNAME=compose-postgres
            - SPRING_DATASOURCE_PASSWORD=compose-postgres
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update     
            - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
            - SPRING.JPA.DATABASE-PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    db:
        image: 'postgres:13.1-alpine'
        container_name: db
        environment:
            - POSTGRES_USER=compose-postgres
            - POSTGRES_PASSWORD=compose-postgres
networks:
    spring-cloud-network:
        driver: bridge