insert into producto (nombre, precio) values ('Juice - Orange, Concentrate!', 91);
insert into producto (nombre, precio) values ('Beef - Ground, Extra Lean, Fresh', 87);
insert into producto (nombre, precio) values ('Cheese - Parmesan Grated', 39);
insert into producto (nombre, precio) values ('Cups 10oz Trans', 67);
insert into producto (nombre, precio) values ('Wine - Beringer Founders Estate', 27);
insert into producto (nombre, precio) values ('Bread - Wheat Baguette', 82);
insert into producto (nombre, precio) values ('Quail - Eggs, Fresh', 3);
insert into producto (nombre, precio) values ('Cheese - Mascarpone', 97);
insert into producto (nombre, precio) values ('Mace', 25);
insert into producto (nombre, precio) values ('Oil - Shortening - All - Purpose', 63);
insert into producto (nombre, precio) values ('Marjoram - Fresh', 60);
insert into producto (nombre, precio) values ('Turnip - White', 74);
insert into producto (nombre, precio) values ('Pork Salted Bellies', 38);
insert into producto (nombre, precio) values ('Longos - Greek Salad', 15);
insert into producto (nombre, precio) values ('Amaretto', 85);
insert into producto (nombre, precio) values ('Godiva White Chocolate', 97);
insert into producto (nombre, precio) values ('Tomatoes - Roma', 61);
insert into producto (nombre, precio) values ('Oven Mitt - 13 Inch', 1);
insert into producto (nombre, precio) values ('Vermouth - White, Cinzano', 72);
insert into producto (nombre, precio) values ('Club Soda - Schweppes, 355 Ml', 38);
insert into producto (nombre, precio) values ('Fenngreek Seed', 1);
insert into producto (nombre, precio) values ('Dill Weed - Dry', 72);
insert into producto (nombre, precio) values ('Pepper - Green', 56);
insert into producto (nombre, precio) values ('Bacardi Breezer - Tropical', 35);
insert into producto (nombre, precio) values ('Wine - Merlot Vina Carmen', 14);
insert into producto (nombre, precio) values ('Sauce - Black Current, Dry Mix', 9);
insert into producto (nombre, precio) values ('Crab - Soft Shell', 17);
insert into producto (nombre, precio) values ('Jameson Irish Whiskey', 19);
insert into producto (nombre, precio) values ('Muffin Chocolate Individual Wrap', 77);
insert into producto (nombre, precio) values ('Mussels - Frozen', 95);
